"""
Paper population pipeline: JSON results -> LaTeX table fragments -> PDF.

Reads the latest experiment results JSON, generates .tex table fragments
in paper/tables/, and compiles the paper.

Usage:
    python paper/populate_paper.py                      # auto-find latest JSON
    python paper/populate_paper.py --json path/to.json  # specific JSON
    python paper/populate_paper.py --compile            # also run pdflatex
"""

import argparse
import glob
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Resolve repo root so we can import from experiments/
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from experiments.generate_paper_tables import (
    METHOD_CATEGORIES,
    LATEX_NAMES,
    build_d_matrix,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TABLES_DIR = REPO_ROOT / "paper" / "tables"
FIGURES_SRC = REPO_ROOT / "experiments" / "outputs" / "regime_detection"
FIGURES_DST = REPO_ROOT / "paper" / "figures"
PAPER_DIR = REPO_ROOT / "paper"
TEX_MAIN = PAPER_DIR / "qcml_geometric_sde.tex"

RESULTS_DIR = REPO_ROOT / "experiments" / "outputs" / "regime_detection"


def find_latest_json() -> Path:
    """Find the most recent comparison_*.json or causal_comparison_*.json."""
    patterns = [
        str(RESULTS_DIR / "causal_comparison_*.json"),
        str(RESULTS_DIR / "comparison_*.json"),
    ]
    candidates = []
    for pat in patterns:
        candidates.extend(glob.glob(pat))

    if not candidates:
        raise FileNotFoundError(
            f"No comparison JSON files found in {RESULTS_DIR}. "
            "Run experiments/regime_comparison.py first."
        )

    # Sort by modification time (newest first)
    candidates.sort(key=os.path.getmtime, reverse=True)
    return Path(candidates[0])


# ---------------------------------------------------------------------------
# Table generation
# ---------------------------------------------------------------------------
def generate_comparison_table(d_matrix, method_names, crisis_keys, summary):
    """Generate paper/tables/table_comparison.tex -- main comparison table.

    Columns: Method | Median d | Mean Rank | Category
    Sorted by median d descending.
    """
    from scipy import stats

    n_crises, n_methods = d_matrix.shape

    # Median d per method
    median_d = np.nanmedian(d_matrix, axis=0)

    # Mean ranks from summary if available, else compute
    if summary and "mean_ranks" in summary:
        rank_lookup = summary["mean_ranks"]
        mean_ranks = np.array([
            rank_lookup.get(m, float("nan")) for m in method_names
        ])
    else:
        d_clean = d_matrix.copy()
        for j in range(n_methods):
            mask = np.isnan(d_clean[:, j])
            d_clean[mask, j] = np.nanmedian(d_clean[:, j])
        ranks = np.zeros_like(d_clean)
        for i in range(n_crises):
            ranks[i] = stats.rankdata(-d_clean[i])
        mean_ranks = np.mean(ranks, axis=0)

    # Friedman stats
    friedman_chi = summary.get("friedman_chi_sq", float("nan")) if summary else float("nan")
    friedman_p = summary.get("friedman_p", float("nan")) if summary else float("nan")

    # Sort by median d descending
    order = np.argsort(-median_d)

    # Find best median d
    best_d = np.nanmax(median_d)

    lines = []
    lines.append(f"% Auto-generated by populate_paper.py")
    lines.append(f"% {n_methods} methods x {n_crises} crises")
    lines.append(f"% Friedman chi-sq = {friedman_chi:.2f}, p = {friedman_p:.2e}")
    lines.append("")
    lines.append(r"\begin{tabular}{lccl}")
    lines.append(r"\toprule")
    lines.append(r"Method & Median $d$ & Mean Rank & Category \\")
    lines.append(r"\midrule")

    for idx in order:
        name = LATEX_NAMES.get(method_names[idx], method_names[idx])
        cat = METHOD_CATEGORIES.get(method_names[idx], "?")
        d_val = median_d[idx]
        rank_val = mean_ranks[idx]

        # Bold the best method
        if abs(d_val - best_d) < 1e-6:
            d_str = r"\textbf{" + f"{d_val:.2f}" + "}"
        else:
            d_str = f"{d_val:.2f}"

        lines.append(f"{name:<25} & {d_str} & {rank_val:.1f} & {cat} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    return "\n".join(lines)


def generate_per_crisis_table(d_matrix, method_names, crisis_keys):
    """Generate paper/tables/table_per_crisis.tex -- per-crisis breakdown.

    Shows top geometric methods + RF + CUSUM across all crises.
    Bold entries where best geometric method beats RF.
    """
    # Select top methods to display
    display_methods = [
        "Berry Phase Rate",
        "QFI Determinant",
        "Multi-Lag Fidelity",
        "Random Forest",
        "CUSUM",
    ]
    # Only include methods that exist in the results
    display_indices = []
    actual_names = []
    for m in display_methods:
        if m in method_names:
            display_indices.append(method_names.index(m))
            actual_names.append(m)

    if not display_indices:
        return "% No matching methods found for per-crisis table"

    # Short names for columns
    short = {
        "Berry Phase Rate": "Berry",
        "QFI Determinant": "QFI Det.",
        "Multi-Lag Fidelity": "Multi-Lag",
        "Random Forest": "RF",
        "CUSUM": "CUSUM",
    }
    header_names = [short.get(n, n[:8]) for n in actual_names]

    # Identify geometric vs supervised indices
    geo_methods = {"Berry Phase Rate", "QFI Determinant", "Multi-Lag Fidelity"}
    geo_indices = [method_names.index(m) for m in geo_methods if m in method_names]
    rf_idx = method_names.index("Random Forest") if "Random Forest" in method_names else -1

    # Pretty crisis names
    crisis_pretty = {
        "1997_asia": "1997 Asia",
        "1998_ltcm": "1998 LTCM",
        "2000_dotcom": "2000 Dotcom",
        "2001_911": "2001 9/11",
        "2001911": "2001 9/11",
        "2007_quant": "2007 Quant",
        "2008_gfc": "2008 GFC",
        "2010_flash": "2010 Flash",
        "2011_euro": "2011 Euro",
        "2015_china": "2015 China",
        "2018_volmageddon": "2018 Volmag.",
        "2018_q4": "2018 Q4",
        "2019_repo": "2019 Repo",
        "2020_covid": "2020 COVID",
        "2022_rates": "2022 Rates",
        "2023_svb": "2023 SVB",
        "2024_carry": "2024 Carry",
    }

    lines = []
    lines.append("% Auto-generated by populate_paper.py")
    lines.append("")
    lines.append(r"\begin{tabular}{l" + "c" * len(display_indices) + "}")
    lines.append(r"\toprule")
    lines.append("Crisis & " + " & ".join(header_names) + r" \\")
    lines.append(r"\midrule")

    for i, crisis in enumerate(crisis_keys):
        name = crisis_pretty.get(crisis, crisis)

        # Determine if best geometric beats RF for this crisis
        rf_d = d_matrix[i, rf_idx] if rf_idx >= 0 else -1
        geo_d_vals = [d_matrix[i, gi] for gi in geo_indices] if geo_indices else []
        best_geo_d = max(geo_d_vals) if geo_d_vals else -1
        best_geo_idx = geo_indices[np.argmax(geo_d_vals)] if geo_d_vals else -1

        vals = []
        for idx in display_indices:
            d_val = d_matrix[i, idx]
            if np.isnan(d_val):
                vals.append("--")
            elif (
                idx in geo_indices
                and idx == best_geo_idx
                and best_geo_d > rf_d
                and rf_idx >= 0
            ):
                vals.append(r"\textbf{" + f"{d_val:.2f}" + "}")
            else:
                vals.append(f"{d_val:.2f}")

        lines.append(f"{name} & " + " & ".join(vals) + r" \\")

    # Median row
    lines.append(r"\midrule")
    medians = []
    for idx in display_indices:
        med = np.nanmedian(d_matrix[:, idx])
        medians.append(f"{med:.2f}")
    lines.append("Median & " + " & ".join(medians) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    # Win count annotation
    if rf_idx >= 0 and geo_indices:
        wins = 0
        for i in range(len(crisis_keys)):
            best_geo = max(d_matrix[i, gi] for gi in geo_indices)
            if best_geo > d_matrix[i, rf_idx]:
                wins += 1
        lines.append("")
        lines.append(f"% Best geometric exceeds RF on {wins}/{len(crisis_keys)} crises")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Figure copying
# ---------------------------------------------------------------------------
def copy_figures():
    """Copy publication figures from experiment outputs to paper/figures/."""
    FIGURES_DST.mkdir(parents=True, exist_ok=True)

    # Patterns of figures to copy
    figure_globs = [
        str(FIGURES_SRC / "*.pdf"),
        str(FIGURES_SRC / "*.png"),
        str(REPO_ROOT / "experiments" / "outputs" / "regime_detection" / "figures" / "*.pdf"),
        str(REPO_ROOT / "experiments" / "outputs" / "regime_detection" / "figures" / "*.png"),
    ]

    copied = 0
    for pat in figure_globs:
        for src_path in glob.glob(pat):
            src = Path(src_path)
            dst = FIGURES_DST / src.name
            if not dst.exists() or src.stat().st_mtime > dst.stat().st_mtime:
                shutil.copy2(src, dst)
                copied += 1

    return copied


# ---------------------------------------------------------------------------
# PDF compilation
# ---------------------------------------------------------------------------
def compile_paper():
    """Compile the paper with pdflatex (3 passes) + bibtex if .bib exists."""
    if not TEX_MAIN.exists():
        print(f"ERROR: {TEX_MAIN} not found")
        return False

    tex_stem = TEX_MAIN.stem

    # Check for .bib file
    bib_file = PAPER_DIR / f"{tex_stem}.bib"
    use_bibtex = bib_file.exists()

    commands = []
    # Pass 1
    commands.append(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_stem]
    )
    # Bibtex (if .bib exists)
    if use_bibtex:
        commands.append(["bibtex", tex_stem])
    # Pass 2
    commands.append(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_stem]
    )
    # Pass 3
    commands.append(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_stem]
    )

    for cmd in commands:
        print(f"  Running: {' '.join(cmd)}")
        result = subprocess.run(
            cmd,
            cwd=str(PAPER_DIR),
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            # pdflatex often returns non-zero on warnings; check for actual errors
            if "Fatal error" in result.stdout or "Emergency stop" in result.stdout:
                print(f"  FAILED: {cmd[0]}")
                # Print last 20 lines of output for debugging
                out_lines = result.stdout.strip().split("\n")
                for line in out_lines[-20:]:
                    print(f"    {line}")
                return False

    pdf_path = PAPER_DIR / f"{tex_stem}.pdf"
    if pdf_path.exists():
        size_mb = pdf_path.stat().st_size / (1024 * 1024)
        print(f"  PDF generated: {pdf_path} ({size_mb:.1f} MB)")
        return True
    else:
        print("  WARNING: PDF not found after compilation")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Paper population pipeline: JSON results -> LaTeX tables -> PDF"
    )
    parser.add_argument(
        "--json",
        type=str,
        default=None,
        help="Path to comparison results JSON (default: auto-find latest)",
    )
    parser.add_argument(
        "--compile",
        action="store_true",
        help="Compile the paper with pdflatex after generating tables",
    )
    parser.add_argument(
        "--copy-figures",
        action="store_true",
        help="Copy figures from experiment outputs to paper/figures/",
    )
    args = parser.parse_args()

    # --- Step 1: Find JSON ---
    if args.json:
        json_path = Path(args.json)
        if not json_path.exists():
            print(f"ERROR: {json_path} does not exist")
            sys.exit(1)
    else:
        json_path = find_latest_json()

    print(f"Loading results from: {json_path.name}")

    with open(json_path) as f:
        data = json.load(f)

    results_dict = data["results"]
    summary = data.get("summary", {})

    # --- Step 2: Build matrix ---
    d_matrix, method_names, crisis_keys = build_d_matrix(results_dict)
    n_methods = len(method_names)
    n_crises = len(crisis_keys)
    print(f"  {n_methods} methods x {n_crises} crises")

    # --- Step 3: Generate table fragments ---
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    # Table: main comparison
    comparison_tex = generate_comparison_table(d_matrix, method_names, crisis_keys, summary)
    comparison_path = TABLES_DIR / "table_comparison.tex"
    comparison_path.write_text(comparison_tex)
    print(f"  Written: {comparison_path.relative_to(REPO_ROOT)}")

    # Table: per-crisis breakdown
    per_crisis_tex = generate_per_crisis_table(d_matrix, method_names, crisis_keys)
    per_crisis_path = TABLES_DIR / "table_per_crisis.tex"
    per_crisis_path.write_text(per_crisis_tex)
    print(f"  Written: {per_crisis_path.relative_to(REPO_ROOT)}")

    # Print summary to stdout
    median_d = np.nanmedian(d_matrix, axis=0)
    order = np.argsort(-median_d)
    print("\n  Method rankings (by median d):")
    for rank, idx in enumerate(order, 1):
        cat = METHOD_CATEGORIES.get(method_names[idx], "?")
        print(f"    {rank:2d}. {method_names[idx]:<25} d={median_d[idx]:.3f}  [{cat}]")

    # Friedman stats
    chi_sq = summary.get("friedman_chi_sq", float("nan"))
    p_val = summary.get("friedman_p", float("nan"))
    print(f"\n  Friedman chi-sq = {chi_sq:.2f}, p = {p_val:.2e}")

    # --- Step 3b: Copy observatory heatmap if available ---
    observatory_heatmap = (
        REPO_ROOT / "experiments" / "outputs" / "observatory" / "orthogonality_heatmap.pdf"
    )
    if observatory_heatmap.exists():
        FIGURES_DST.mkdir(parents=True, exist_ok=True)
        dst = FIGURES_DST / "orthogonality_heatmap.pdf"
        shutil.copy2(observatory_heatmap, dst)
        print(f"  Copied observatory heatmap to {dst.relative_to(REPO_ROOT)}")

    # --- Step 4: Copy figures ---
    if args.copy_figures:
        n_copied = copy_figures()
        print(f"\n  Copied {n_copied} figure(s) to paper/figures/")

    # --- Step 5: Compile ---
    if args.compile:
        print("\nCompiling paper...")
        success = compile_paper()
        if not success:
            print("Compilation failed. Check paper/*.log for details.")
            sys.exit(1)
        print("Compilation complete.")

    print("\nDone.")


if __name__ == "__main__":
    main()
