"""
Paper population pipeline: JSON results -> LaTeX table fragments -> PDF.

Reads the latest experiment results JSON, generates .tex table fragments
in paper/tables/, and compiles the paper.

Usage:
    python paper/populate_paper.py                      # auto-find latest JSON
    python paper/populate_paper.py --json path/to.json  # specific JSON
    python paper/populate_paper.py --compile            # also run pdflatex
"""

import argparse
import glob
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Resolve repo root so we can import from experiments/
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from experiments.generate_paper_tables import (
    METHOD_CATEGORIES,
    LATEX_NAMES,
    build_d_matrix,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TABLES_DIR = REPO_ROOT / "paper" / "tables"
FIGURES_SRC = REPO_ROOT / "experiments" / "outputs" / "regime_detection"
FIGURES_DST = REPO_ROOT / "paper" / "figures"
PAPER_DIR = REPO_ROOT / "paper"
TEX_MAIN = PAPER_DIR / "qcml_geometric_sde.tex"

RESULTS_DIR = REPO_ROOT / "experiments" / "outputs" / "regime_detection"
FUSION_DIR = REPO_ROOT / "experiments" / "outputs" / "fusion"


def find_latest_json() -> Path:
    """Find the most recent comparison_*.json or causal_comparison_*.json."""
    patterns = [
        str(RESULTS_DIR / "causal_comparison_*.json"),
        str(RESULTS_DIR / "comparison_*.json"),
    ]
    candidates = []
    for pat in patterns:
        candidates.extend(glob.glob(pat))

    if not candidates:
        raise FileNotFoundError(
            f"No comparison JSON files found in {RESULTS_DIR}. "
            "Run experiments/regime_comparison.py first."
        )

    # Sort by modification time (newest first)
    candidates.sort(key=os.path.getmtime, reverse=True)
    return Path(candidates[0])


# ---------------------------------------------------------------------------
# Table generation
# ---------------------------------------------------------------------------
def generate_comparison_table(d_matrix, method_names, crisis_keys, summary):
    """Generate paper/tables/table_comparison.tex -- main comparison table.

    Columns: Method | Median d | Mean Rank | Category
    Sorted by median d descending.
    """
    from scipy import stats

    n_crises, n_methods = d_matrix.shape

    # Median d per method
    median_d = np.nanmedian(d_matrix, axis=0)

    # Mean ranks from summary if available, else compute
    if summary and "mean_ranks" in summary:
        rank_lookup = summary["mean_ranks"]
        mean_ranks = np.array([
            rank_lookup.get(m, float("nan")) for m in method_names
        ])
    else:
        d_clean = d_matrix.copy()
        for j in range(n_methods):
            mask = np.isnan(d_clean[:, j])
            d_clean[mask, j] = np.nanmedian(d_clean[:, j])
        ranks = np.zeros_like(d_clean)
        for i in range(n_crises):
            ranks[i] = stats.rankdata(-d_clean[i])
        mean_ranks = np.mean(ranks, axis=0)

    # Friedman stats
    friedman_chi = summary.get("friedman_chi_sq", float("nan")) if summary else float("nan")
    friedman_p = summary.get("friedman_p", float("nan")) if summary else float("nan")

    # Sort by median d descending
    order = np.argsort(-median_d)

    # Find best median d
    best_d = np.nanmax(median_d)

    lines = []
    lines.append(f"% Auto-generated by populate_paper.py")
    lines.append(f"% {n_methods} methods x {n_crises} crises")
    lines.append(f"% Friedman chi-sq = {friedman_chi:.2f}, p = {friedman_p:.2e}")
    lines.append("")
    lines.append(r"\begin{tabular}{lccl}")
    lines.append(r"\toprule")
    lines.append(r"Method & Median $d$ & Mean Rank & Category \\")
    lines.append(r"\midrule")

    for idx in order:
        name = LATEX_NAMES.get(method_names[idx], method_names[idx])
        cat = METHOD_CATEGORIES.get(method_names[idx], "?")
        d_val = median_d[idx]
        rank_val = mean_ranks[idx]

        # Bold the best method
        if abs(d_val - best_d) < 1e-6:
            d_str = r"\textbf{" + f"{d_val:.2f}" + "}"
        else:
            d_str = f"{d_val:.2f}"

        lines.append(f"{name:<25} & {d_str} & {rank_val:.1f} & {cat} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    return "\n".join(lines)


def generate_per_crisis_table(d_matrix, method_names, crisis_keys):
    """Generate paper/tables/table_per_crisis.tex -- per-crisis breakdown.

    Shows top geometric methods + RF + CUSUM across all crises.
    Bold entries where best geometric method beats RF.
    """
    # Select top methods to display
    display_methods = [
        "Reduced Purity",
        "Berry Phase Rate",
        "QFI Determinant",
        "Hamilton MS",
        "CUSUM",
    ]
    # Only include methods that exist in the results
    display_indices = []
    actual_names = []
    for m in display_methods:
        if m in method_names:
            display_indices.append(method_names.index(m))
            actual_names.append(m)

    if not display_indices:
        return "% No matching methods found for per-crisis table"

    # Short names for columns
    short = {
        "Reduced Purity": "Red. Pur.",
        "Berry Phase Rate": "Berry",
        "QFI Determinant": "QFI Det.",
        "Hamilton MS": "Ham. MS",
        "CUSUM": "CUSUM",
    }
    header_names = [short.get(n, n[:8]) for n in actual_names]

    # Identify geometric vs classical indices for bolding
    geo_methods = {"Reduced Purity", "Berry Phase Rate", "QFI Determinant"}
    geo_indices = [method_names.index(m) for m in geo_methods if m in method_names]
    rf_idx = method_names.index("Hamilton MS") if "Hamilton MS" in method_names else -1

    # Pretty crisis names
    crisis_pretty = {
        "1997_asia": "1997 Asia",
        "1998_ltcm": "1998 LTCM",
        "2000_dotcom": "2000 Dotcom",
        "2001_911": "2001 9/11",
        "2001911": "2001 9/11",
        "2007_quant": "2007 Quant",
        "2008_gfc": "2008 GFC",
        "2010_flash": "2010 Flash",
        "2011_euro": "2011 Euro",
        "2013_taper": "2013 Taper",
        "2015_china": "2015 China",
        "2016_brexit": "2016 Brexit",
        "2018_volmageddon": "2018 Volmag.",
        "2018_q4": "2018 Q4",
        "2019_repo": "2019 Repo",
        "2020_covid": "2020 COVID",
        "2021_meme": "2021 Meme",
        "2022_rates": "2022 Rates",
        "2023_svb": "2023 SVB",
        "2024_carry": "2024 Carry",
    }

    lines = []
    lines.append("% Auto-generated by populate_paper.py")
    lines.append("")
    lines.append(r"\begin{tabular}{l" + "c" * len(display_indices) + "}")
    lines.append(r"\toprule")
    lines.append("Crisis & " + " & ".join(header_names) + r" \\")
    lines.append(r"\midrule")

    for i, crisis in enumerate(crisis_keys):
        name = crisis_pretty.get(crisis, crisis)

        # Determine if best geometric beats RF for this crisis
        rf_d = d_matrix[i, rf_idx] if rf_idx >= 0 else -1
        geo_d_vals = [d_matrix[i, gi] for gi in geo_indices] if geo_indices else []
        best_geo_d = max(geo_d_vals) if geo_d_vals else -1
        best_geo_idx = geo_indices[np.argmax(geo_d_vals)] if geo_d_vals else -1

        vals = []
        for idx in display_indices:
            d_val = d_matrix[i, idx]
            if np.isnan(d_val):
                vals.append("--")
            elif (
                idx in geo_indices
                and idx == best_geo_idx
                and best_geo_d > rf_d
                and rf_idx >= 0
            ):
                vals.append(r"\textbf{" + f"{d_val:.2f}" + "}")
            else:
                vals.append(f"{d_val:.2f}")

        lines.append(f"{name} & " + " & ".join(vals) + r" \\")

    # Median row
    lines.append(r"\midrule")
    medians = []
    for idx in display_indices:
        med = np.nanmedian(d_matrix[:, idx])
        medians.append(f"{med:.2f}")
    lines.append("Median & " + " & ".join(medians) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    # Win count annotation
    if rf_idx >= 0 and geo_indices:
        wins = 0
        for i in range(len(crisis_keys)):
            best_geo = max(d_matrix[i, gi] for gi in geo_indices)
            if best_geo > d_matrix[i, rf_idx]:
                wins += 1
        lines.append("")
        lines.append(f"% Best geometric exceeds RF on {wins}/{len(crisis_keys)} crises")

    return "\n".join(lines)


def generate_holdout_table(holdout_path):
    """Generate paper/tables/table_holdout.tex from holdout JSON.

    Columns: Method | 2022 Rates d | SVB d | Carry d | Mean d
    Top 15 methods, sorted by mean d, best per-crisis column bolded.
    """
    with open(holdout_path) as f:
        data = json.load(f)

    crises = ["2022_rates", "2023_svb", "2024_carry"]
    crisis_labels = ["Rates", "SVB", "Carry"]

    rows = []
    for method, crisis_data in data["per_method"].items():
        ds = [crisis_data.get(c, {}).get("d", float("nan")) for c in crises]
        mean_d = np.nanmean(ds)
        rows.append((method, ds, mean_d))

    rows.sort(key=lambda x: -x[2])

    # Find best d per crisis column
    best_per_col = []
    for col_idx in range(len(crises)):
        col_vals = [r[1][col_idx] for r in rows if not np.isnan(r[1][col_idx])]
        best_per_col.append(max(col_vals) if col_vals else 0)
    best_mean = rows[0][2] if rows else 0

    lines = []
    lines.append("% Auto-generated by populate_paper.py (holdout)")
    lines.append(f"% {len(data['per_method'])} methods, 3 holdout crises")
    lines.append(f"% Cutoff: {data['metadata']['cutoff_date']}")
    lines.append("")
    lines.append(r"\begin{tabular}{lcccc}")
    lines.append(r"\toprule")
    lines.append("Method & " + " & ".join(crisis_labels) + r" & Mean $d$ \\")
    lines.append(r"\midrule")

    for method, ds, mean_d in rows[:15]:
        name = LATEX_NAMES.get(method, method)
        vals = []
        for col_idx, d_val in enumerate(ds):
            if np.isnan(d_val):
                vals.append("--")
            elif abs(d_val - best_per_col[col_idx]) < 1e-6:
                vals.append(r"\textbf{" + f"{d_val:.2f}" + "}")
            else:
                vals.append(f"{d_val:.2f}")
        mean_str = (r"\textbf{" + f"{mean_d:.2f}" + "}") if abs(mean_d - best_mean) < 1e-6 else f"{mean_d:.2f}"
        lines.append(f"{name:<25} & " + " & ".join(vals) + f" & {mean_str}" + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    return "\n".join(lines)


def generate_lead_time_table(lead_time_path):
    """Generate paper/tables/table_lead_time.tex from lead time JSON.

    Columns: Method | Mean Lead (days) | Median Lead | Det. Rate (n/17) | Category
    All methods that detected >= 1 crisis, sorted by detection rate * mean lead.
    """
    with open(lead_time_path) as f:
        data = json.load(f)

    rows = []
    for method, stats in data["summary"].items():
        n_det = stats["n_detected"]
        n_tot = stats["n_total"]
        mean_lead = stats["mean_lead_time"]
        median_lead = stats["median_lead_time"]
        if n_det == 0:
            continue
        score = (n_det / n_tot) * (mean_lead or 0)
        rows.append((method, mean_lead or 0, median_lead or 0, n_det, n_tot, score))

    rows.sort(key=lambda x: -x[5])

    # Friedman stats from lead time JSON
    friedman = data.get("statistical_tests", {}).get("friedman", {})
    chi_sq = friedman.get("chi_sq", float("nan"))
    p_val = friedman.get("p_value", float("nan"))

    lines = []
    lines.append("% Auto-generated by populate_paper.py (lead time)")
    lines.append(f"% Friedman chi-sq = {chi_sq:.1f}, p = {p_val:.1e}")
    lines.append("")
    lines.append(r"\begin{tabular}{lccll}")
    lines.append(r"\toprule")
    lines.append(r"Method & Mean Lead & Median Lead & Det.\ Rate & Category \\")
    lines.append(r"\midrule")

    for method, mean_lead, median_lead, n_det, n_tot, score in rows:
        name = LATEX_NAMES.get(method, method)
        cat = METHOD_CATEGORIES.get(method, "?")
        det_str = f"{n_det}/{n_tot}"
        lines.append(
            f"{name:<25} & {mean_lead:.0f} & {median_lead:.0f} & {det_str} & {cat}" + r" \\"
        )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    return "\n".join(lines)


def generate_fusion_table(fusion_path):
    """Generate paper/tables/table_fusion.tex from fusion results JSON.

    Columns: Method | Mean d | Median d | CV | Category
    Top 5 individuals + all 7 fusion methods, sorted by mean d.
    """
    with open(fusion_path) as f:
        data = json.load(f)

    aggregate = data["aggregate"]
    friedman = data.get("friedman", {})
    chi_sq = friedman.get("chi_sq", float("nan"))
    p_val = friedman.get("p_value", float("nan"))

    # Separate individuals and fusion methods
    individuals = [r for r in aggregate if r["category"] == "individual"]
    fusions = [r for r in aggregate if r["category"] != "individual"]

    # Top 5 individuals by mean d
    individuals.sort(key=lambda x: -x["mean_d"])
    top_individuals = individuals[:5]

    # All fusion methods sorted by mean d
    fusions.sort(key=lambda x: -x["mean_d"])

    rows = top_individuals + fusions

    # Category labels for fusion types
    cat_labels = {
        "individual": "Individual",
        "flat_fusion": "Flat Fusion",
        "hierarchical": "Hierarchical",
        "regime_adaptive": "Regime-Adaptive",
        "sprt": "SPRT",
    }

    lines = []
    lines.append("% Auto-generated by populate_paper.py (fusion)")
    lines.append(f"% Friedman chi-sq = {chi_sq:.2f}, p = {p_val:.4f}")
    lines.append("")
    lines.append(r"\begin{tabular}{lcccc}")
    lines.append(r"\toprule")
    lines.append(r"Method & Mean $d$ & Median $d$ & CV & Category \\")
    lines.append(r"\midrule")

    best_mean = max(r["mean_d"] for r in rows)
    added_rule = False

    for row in rows:
        if not added_rule and row["category"] != "individual":
            lines.append(r"\midrule")
            added_rule = True
        name = LATEX_NAMES.get(row["method"], row["method"])
        mean_d = row["mean_d"]
        median_d = row["median_d"]
        std_d = row["std_d"]
        cv = std_d / mean_d if mean_d > 0 else float("inf")
        cat = cat_labels.get(row["category"], row["category"])

        mean_str = f"{mean_d:.3f}"
        if abs(mean_d - best_mean) < 1e-6:
            mean_str = r"\textbf{" + mean_str + "}"

        lines.append(
            f"{name:<25} & {mean_str} & {median_d:.3f} & {cv:.2f} & {cat}" + r" \\"
        )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    return "\n".join(lines)


def generate_fusion_holdout_table(holdout_path):
    """Generate paper/tables/table_fusion_holdout.tex from fusion holdout JSON.

    Shows top 3 fusion methods + Reduced Purity + Spectral Entropy.
    Columns: Method | per-crisis d values | Mean d.  Bold best per-column.
    """
    with open(holdout_path) as f:
        data = json.load(f)

    crises = data["metadata"]["crises"]
    crisis_labels = {
        "2021_meme": "Meme",
        "2022_rates": "Rates",
        "2023_svb": "SVB",
        "2024_carry": "Carry",
    }

    # Build per-method aggregates
    methods = {}
    for row in data["per_crisis"]:
        m = row["method"]
        if m not in methods:
            methods[m] = {"per_crisis": {}, "ds": []}
        methods[m]["per_crisis"][row["crisis"]] = row["d"]
        methods[m]["ds"].append(row["d"])

    # Select display methods: top 3 fusion + 2 key individuals
    fusion_names = [
        "Regime-Adaptive",
        "Hierarchical Rank",
        "Flat Rank Fusion",
    ]
    individual_names = [
        "Reduced Purity",
        "Spectral Entropy",
    ]
    display_methods = fusion_names + individual_names
    display_methods = [m for m in display_methods if m in methods]

    # Find best per column
    best_per_col = {}
    for c in crises:
        col_vals = [methods[m]["per_crisis"].get(c, float("nan"))
                    for m in display_methods
                    if not np.isnan(methods[m]["per_crisis"].get(c, float("nan")))]
        best_per_col[c] = max(col_vals) if col_vals else 0

    mean_ds = {m: np.mean(methods[m]["ds"]) for m in display_methods}
    best_mean = max(mean_ds.values())

    col_headers = [crisis_labels.get(c, c) for c in crises]

    lines = []
    lines.append("% Auto-generated by populate_paper.py (fusion holdout)")
    lines.append(f"% {len(crises)} holdout crises")
    lines.append("")
    lines.append(r"\begin{tabular}{l" + "c" * len(crises) + "c}")
    lines.append(r"\toprule")
    lines.append(
        "Method & " + " & ".join(col_headers) + r" & Mean $d$ \\"
    )
    lines.append(r"\midrule")

    added_rule = False
    for m in display_methods:
        if not added_rule and m in individual_names:
            lines.append(r"\midrule")
            added_rule = True
        name = LATEX_NAMES.get(m, m)
        vals = []
        for c in crises:
            d_val = methods[m]["per_crisis"].get(c, float("nan"))
            if np.isnan(d_val):
                vals.append("--")
            elif abs(d_val - best_per_col[c]) < 1e-6:
                vals.append(r"\textbf{" + f"{d_val:.2f}" + "}")
            else:
                vals.append(f"{d_val:.2f}")
        mean_d = mean_ds[m]
        mean_str = f"{mean_d:.3f}"
        if abs(mean_d - best_mean) < 1e-3:
            mean_str = r"\textbf{" + mean_str + "}"
        lines.append(
            f"{name:<25} & " + " & ".join(vals) + f" & {mean_str}" + r" \\"
        )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Figure copying
# ---------------------------------------------------------------------------
def copy_figures():
    """Copy publication figures from experiment outputs to paper/figures/."""
    FIGURES_DST.mkdir(parents=True, exist_ok=True)

    # Patterns of figures to copy
    figure_globs = [
        str(FIGURES_SRC / "*.pdf"),
        str(FIGURES_SRC / "*.png"),
        str(REPO_ROOT / "experiments" / "outputs" / "regime_detection" / "figures" / "*.pdf"),
        str(REPO_ROOT / "experiments" / "outputs" / "regime_detection" / "figures" / "*.png"),
    ]

    copied = 0
    for pat in figure_globs:
        for src_path in glob.glob(pat):
            src = Path(src_path)
            dst = FIGURES_DST / src.name
            if not dst.exists() or src.stat().st_mtime > dst.stat().st_mtime:
                shutil.copy2(src, dst)
                copied += 1

    return copied


# ---------------------------------------------------------------------------
# PDF compilation
# ---------------------------------------------------------------------------
def compile_paper():
    """Compile the paper with pdflatex (3 passes) + bibtex if .bib exists."""
    if not TEX_MAIN.exists():
        print(f"ERROR: {TEX_MAIN} not found")
        return False

    tex_stem = TEX_MAIN.stem

    # Check for .bib file
    bib_file = PAPER_DIR / f"{tex_stem}.bib"
    use_bibtex = bib_file.exists()

    commands = []
    # Pass 1
    commands.append(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_stem]
    )
    # Bibtex (if .bib exists)
    if use_bibtex:
        commands.append(["bibtex", tex_stem])
    # Pass 2
    commands.append(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_stem]
    )
    # Pass 3
    commands.append(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_stem]
    )

    for cmd in commands:
        print(f"  Running: {' '.join(cmd)}")
        result = subprocess.run(
            cmd,
            cwd=str(PAPER_DIR),
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            # pdflatex often returns non-zero on warnings; check for actual errors
            if "Fatal error" in result.stdout or "Emergency stop" in result.stdout:
                print(f"  FAILED: {cmd[0]}")
                # Print last 20 lines of output for debugging
                out_lines = result.stdout.strip().split("\n")
                for line in out_lines[-20:]:
                    print(f"    {line}")
                return False

    pdf_path = PAPER_DIR / f"{tex_stem}.pdf"
    if pdf_path.exists():
        size_mb = pdf_path.stat().st_size / (1024 * 1024)
        print(f"  PDF generated: {pdf_path} ({size_mb:.1f} MB)")
        return True
    else:
        print("  WARNING: PDF not found after compilation")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Paper population pipeline: JSON results -> LaTeX tables -> PDF"
    )
    parser.add_argument(
        "--json",
        type=str,
        default=None,
        help="Path to comparison results JSON (default: auto-find latest)",
    )
    parser.add_argument(
        "--compile",
        action="store_true",
        help="Compile the paper with pdflatex after generating tables",
    )
    parser.add_argument(
        "--copy-figures",
        action="store_true",
        help="Copy figures from experiment outputs to paper/figures/",
    )
    args = parser.parse_args()

    # --- Step 1: Find JSON ---
    if args.json:
        json_path = Path(args.json)
        if not json_path.exists():
            print(f"ERROR: {json_path} does not exist")
            sys.exit(1)
    else:
        json_path = find_latest_json()

    print(f"Loading results from: {json_path.name}")

    with open(json_path) as f:
        data = json.load(f)

    results_dict = data["results"]
    summary = data.get("summary", {})

    # --- Step 2: Build matrix ---
    d_matrix, method_names, crisis_keys = build_d_matrix(results_dict)
    n_methods = len(method_names)
    n_crises = len(crisis_keys)
    print(f"  {n_methods} methods x {n_crises} crises")

    # --- Step 3: Generate table fragments ---
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    # Table: main comparison
    comparison_tex = generate_comparison_table(d_matrix, method_names, crisis_keys, summary)
    comparison_path = TABLES_DIR / "table_comparison.tex"
    comparison_path.write_text(comparison_tex)
    print(f"  Written: {comparison_path.relative_to(REPO_ROOT)}")

    # Table: per-crisis breakdown
    per_crisis_tex = generate_per_crisis_table(d_matrix, method_names, crisis_keys)
    per_crisis_path = TABLES_DIR / "table_per_crisis.tex"
    per_crisis_path.write_text(per_crisis_tex)
    print(f"  Written: {per_crisis_path.relative_to(REPO_ROOT)}")

    # Table: holdout (find latest)
    holdout_dir = REPO_ROOT / "experiments" / "outputs" / "holdout"
    holdout_candidates = sorted(glob.glob(str(holdout_dir / "holdout_*.json")))
    if holdout_candidates:
        holdout_path = Path(holdout_candidates[-1])
        holdout_tex = generate_holdout_table(holdout_path)
        holdout_out = TABLES_DIR / "table_holdout.tex"
        holdout_out.write_text(holdout_tex)
        print(f"  Written: {holdout_out.relative_to(REPO_ROOT)} (from {holdout_path.name})")
    else:
        print("  SKIP: no holdout JSON found")

    # Table: lead time (find latest)
    lead_time_dir = REPO_ROOT / "experiments" / "outputs" / "lead_time"
    lead_time_candidates = sorted(glob.glob(str(lead_time_dir / "lead_time_*.json")))
    if lead_time_candidates:
        lead_time_path = Path(lead_time_candidates[-1])
        lead_time_tex = generate_lead_time_table(lead_time_path)
        lead_time_out = TABLES_DIR / "table_lead_time.tex"
        lead_time_out.write_text(lead_time_tex)
        print(f"  Written: {lead_time_out.relative_to(REPO_ROOT)} (from {lead_time_path.name})")
    else:
        print("  SKIP: no lead time JSON found")

    # Table: fusion (find latest)
    fusion_candidates = sorted(glob.glob(str(FUSION_DIR / "fusion_results_*.json")))
    # Separate full vs holdout by checking metadata preset
    fusion_full_path = None
    fusion_holdout_path = None
    for fc in fusion_candidates:
        with open(fc) as f:
            meta = json.load(f).get("metadata", {})
        if meta.get("preset") == "holdout":
            fusion_holdout_path = Path(fc)
        else:
            fusion_full_path = Path(fc)

    if fusion_full_path:
        fusion_tex = generate_fusion_table(fusion_full_path)
        fusion_out = TABLES_DIR / "table_fusion.tex"
        fusion_out.write_text(fusion_tex)
        print(f"  Written: {fusion_out.relative_to(REPO_ROOT)} (from {fusion_full_path.name})")
    else:
        print("  SKIP: no fusion full JSON found")

    if fusion_holdout_path:
        fusion_holdout_tex = generate_fusion_holdout_table(fusion_holdout_path)
        fusion_holdout_out = TABLES_DIR / "table_fusion_holdout.tex"
        fusion_holdout_out.write_text(fusion_holdout_tex)
        print(
            f"  Written: {fusion_holdout_out.relative_to(REPO_ROOT)}"
            f" (from {fusion_holdout_path.name})"
        )
    else:
        print("  SKIP: no fusion holdout JSON found")

    # Print summary to stdout
    median_d = np.nanmedian(d_matrix, axis=0)
    order = np.argsort(-median_d)
    print("\n  Method rankings (by median d):")
    for rank, idx in enumerate(order, 1):
        cat = METHOD_CATEGORIES.get(method_names[idx], "?")
        print(f"    {rank:2d}. {method_names[idx]:<25} d={median_d[idx]:.3f}  [{cat}]")

    # Friedman stats
    chi_sq = summary.get("friedman_chi_sq", float("nan"))
    p_val = summary.get("friedman_p", float("nan"))
    print(f"\n  Friedman chi-sq = {chi_sq:.2f}, p = {p_val:.2e}")

    # --- Step 3b: Copy observatory heatmap if available ---
    observatory_heatmap = (
        REPO_ROOT / "experiments" / "outputs" / "observatory" / "orthogonality_heatmap.pdf"
    )
    if observatory_heatmap.exists():
        FIGURES_DST.mkdir(parents=True, exist_ok=True)
        dst = FIGURES_DST / "orthogonality_heatmap.pdf"
        shutil.copy2(observatory_heatmap, dst)
        print(f"  Copied observatory heatmap to {dst.relative_to(REPO_ROOT)}")

    # --- Step 4: Copy figures ---
    if args.copy_figures:
        n_copied = copy_figures()
        print(f"\n  Copied {n_copied} figure(s) to paper/figures/")

    # --- Step 5: Compile ---
    if args.compile:
        print("\nCompiling paper...")
        success = compile_paper()
        if not success:
            print("Compilation failed. Check paper/*.log for details.")
            sys.exit(1)
        print("Compilation complete.")

    print("\nDone.")


if __name__ == "__main__":
    main()
